wayne-love/ESPySpa

.github/workflows/build.yaml, lib/SpaNetController/SpaNetController.cpp, lib/WebUI/WebUI.cpp, lib/WebUI/WebUI.h, platformio.ini, src/main.cpp
Here's my first PR into the repo - please take a look and let me know. I wanted to get a first PR up so that the process for review got kicked off nice and quick! I haven't tested this on device yet...
=> Adding ESP8266 build support, and a GitHub Action

lib/SpaNetInterface/SpaNetInterface.cpp, lib/SpaNetInterface/SpaNetInterface.h, lib/SpaNetInterface/SpaNetProperties.h, src/main.cpp
=> Additional features

lib/SpaInterface/SpaInterface.cpp, lib/SpaInterface/SpaInterface.h, lib/SpaInterface/SpaProperties.h, lib/WebUI/WebUI.h, src/main.cpp
Add ability to read/set sleep timers and spa mode. Includes some minor fixes/tweaks.
=> Add sleep timers and spa mode

lib/SpaInterface/SpaInterface.cpp, lib/SpaInterface/SpaInterface.h, lib/WebUI/WebUI.cpp, lib/WebUI/WebUI.h, platformio.ini, src/main.cpp
This PR includes:
* Update to Json 7.
* Tweaks to the WebUI in preperation for enabling a json interface.
* Updates to platformio for the new board (not tested yet - it should arrive soon).
* Lights data move back into the common topic.
* Started to set up the config for prettier, nested json.
See commits for details. Happy to discuss.
=> Json 7. lights back into a common topic and more

lib/WebUI/WebUI.cpp, lib/WebUI/WebUI.h, platformio.ini, src/main.cpp
minors tweaks to add support for spa-controller-pcb
=> WebUI support ESP8266 and ESP32 and minor tweaks

platformio.ini, src/main.cpp
If a second reboot occurs within REBOOT_THRESHOLD (20 sec), then start Wi-Fi Manager
=> If a second reboot occurs within REBOOT_THRESHOLD (20 sec),

lib/SpaInterface/SpaProperties.h, lib/SpaUtils/SpaUtils.cpp, lib/SpaUtils/SpaUtils.h, lib/WebUI/WebUI.cpp, lib/WebUI/WebUI.h, src/main.cpp
Move the following functions to SpaUtils:
generateStatusJson
convertToInteger
convertToTime
Update json format
=> Add SpaUtils and update json format

.github/workflows/build.yaml, lib/SpaInterface/SpaProperties.h, lib/SpaUtils/SpaUtils.h
Apply build workflow on push as well as pull request.
fix build errors - changed Time.h to time.h
=> Fix github build

lib/HAAutoDiscovery/HAAutoDiscovery.cpp, lib/HAAutoDiscovery/HAAutoDiscovery.h, lib/SpaInterface/SpaProperties.h, lib/SpaUtils/SpaUtils.cpp, src/main.cpp
Removed the use of std::vector library
=> Vector removal

CHANGELOG.md, lib/SpaInterface/SpaInterface.h
Change statusResponseMinFields to 288 to support SVM1
=> First attempt to support SVM1

lib/Config/Config.cpp, lib/Config/Config.h, lib/SpaInterface/SpaInterface.h, lib/SpaUtils/SpaUtils.h, lib/WebUI/WebUI.cpp, lib/WebUI/WebUI.h, merge-bin.py, platformio.ini, src/main.cpp
- Remove double reboot
- Start Wi-Fi Manager of no config exists
- Rename Common to Config
- Fixes a little bug
- Debug moving from Common to main - this is prep work for Config class creation
=> Lots of little changes

lib/Config/Config.cpp, lib/Config/Config.h, lib/HAAutoDiscovery/HAAutoDiscovery.cpp, lib/HAAutoDiscovery/HAAutoDiscovery.h, lib/SpaInterface/SpaInterface.cpp, lib/SpaInterface/SpaInterface.h, lib/WebUI/WebUI.cpp, lib/WebUI/WebUI.h, src/main.cpp
- Minor WebUI updates
- Wi-Fi Manager launched from WebUI changed to callback
- Rename variables and classes
- Change Config to a class
- Set up callbacks for config changes
- Immediately apply poll frequency
- Framework for MQTT changes in place
=> Change Config to a class and other updates

get_version.py, lib/HAAutoDiscovery/HAAutoDiscovery.cpp, lib/HAAutoDiscovery/HAAutoDiscovery.h, lib/SpaUtils/SpaUtils.cpp, lib/WebUI/WebUI.h, platformio.ini, src/main.cpp
1. Add Spa manufacturer, controller model, and link to ESP web interface. https://github.com/wayne-love/sn_esp32/issues/55
2. Possible fix for strange times on timers. https://github.com/wayne-love/sn_esp32/issues/35
3. Don't publish entities that aren't connected/supported. https://github.com/wayne-love/sn_esp32/issues/54
=> Various updates to fixes issues

lib/Config/Config.cpp, lib/Config/Config.h, lib/WebUI/WebUI.cpp, src/main.cpp
Converting String to c_str was resulting in the pointer to the c_str becoming invalid.
This also appears to fix the bug and enable mqttClient to reconnect after change.
=> Config updates. 

lib/WebUI/WebUI.cpp, lib/WebUI/WebUI.h
This is a suggestion, I'm not fixed on this, but it makes it simple to set the spa time with a single click in the web UI.
=> Add one click to set Spa time to WebUI

lib/SpaUtils/SpaUtils.cpp
I've only changed the code comments - nothing else.
=> Update comments only

lib/MultiBlinker/MultiBlinker.cpp, lib/MultiBlinker/MultiBlinker.h, platformio.ini
Jonathan and I have tested, this resolves a bug with single LED boards.
=> MultiBlinker bug fixes and add array to define timers

lib/SpaInterface/SpaInterface.cpp, lib/SpaInterface/SpaInterface.h
Reduced statusResponseMinFields to 283 to support SV3 controller. We need to review data validation. Suggest we look at checking to ensure each row contains data.
=> Support SV3 controller.

data/www/espa.js, data/www/fota.htm, data/www/index.htm, data/www/styles.css, lib/SpaUtils/SpaUtils.cpp, lib/SpaUtils/SpaUtils.h, src/main.cpp
Updates:
1. Minor tweaks
2. Firmware Over The Air page updates to detect new versions of firmware
=> New web UI

CHANGELOG.md, lib/Config/Config.cpp, lib/Config/Config.h, lib/WebUI/WebUI.cpp, lib/WebUI/WebUI.h, src/main.cpp
This is how I'm doing OTA file system updates. I've tried numerous things to force it to LittleFS, but had not luck.
=> Ota filesystem update

src/main.cpp
entity advertises fine in mqtt, HA isnt complaining in energy dashboard anymore.
=> fixes issue #58

data/www/espa.js
version from github, before we had the current running version. This would result in reporting an available update when there wasn't one.
fixes #99
=> Fix bug where sometimes we would get the release

README.md
Update the readme to include the hotspot password
=> Update the readme to include the hotspot password
